//! cloudflared: the first tunnel provider. A tunnel is a supervised process
//! like any other service, but it exists to serve something else, so it is
//! only ever a target and never a service on its own.

use comb::{
    BinarySpec, Error, HealthCheck, Notice, Paths, Platform, Port, Probe, Result, ServiceSpec,
};

use crate::{Pin, Request, ServiceAdapter};

pub struct Cloudflared;

/// Generated by `scripts/pin-release.sh cloudflared <version>`.
const PINS: &[Pin] = &[Pin {
    version: "2026.8.3",
    platform: Platform::MacosArm64,
    url: "https://github.com/cloudflare/cloudflared/releases/download/2026.8.3/cloudflared-darwin-arm64.tgz",
    sha256: "40c9144d86df8937c5b43293a1f7d2d2107029aa74725023dd46b1b27154352f",
    size: 19_197_606,
    strip_components: 0,
}];

/// The only port a tunnel has is the one it reports on. Nobody connects to
/// it but the probe, and each tunnel gets its own.
const PORTS: &[(&str, u16)] = &[("metrics", 20241)];

/// The public host every quick tunnel is given.
pub const PUBLIC_SUFFIX: &str = "trycloudflare.com";

/// The word to lift out of the box cloudflared draws around the url. With
/// the dot, so "Requesting new quick Tunnel on trycloudflare.com..." a few
/// lines earlier is not mistaken for it.
const MARKER: &str = ".trycloudflare.com";

impl ServiceAdapter for Cloudflared {
    fn name(&self) -> &'static str {
        "cloudflared"
    }

    fn display_name(&self) -> &'static str {
        "Tunnel"
    }

    fn program(&self) -> &'static str {
        "cloudflared"
    }

    fn pins(&self) -> &'static [Pin] {
        PINS
    }

    fn default_version(&self) -> &'static str {
        "2026.8.3"
    }

    fn default_ports(&self) -> &'static [(&'static str, u16)] {
        PORTS
    }

    fn spec(&self, request: &Request, paths: &Paths) -> Result<ServiceSpec> {
        // A tunnel with nothing behind it is not a thing to start.
        let origin = request.origin.as_ref().ok_or_else(|| {
            Error::InvalidId("a tunnel needs something to expose, which skep share gives it".into())
        })?;
        let version = request.resolve_version(self)?;
        let release = crate::release(self, &version)?;
        let id = request.instance(self, &version)?;
        let metrics = request.port(self, "metrics")?;
        let data_dir = paths.data_dir(&id);

        let mut args = vec![
            "tunnel".to_string(),
            // The binary never replaces itself: versions are pinned here.
            "--no-autoupdate".to_string(),
            "--url".to_string(),
            origin.url.clone(),
            "--metrics".to_string(),
            format!("127.0.0.1:{metrics}"),
        ];
        if let Some(host) = &origin.host {
            // Reached on loopback, named in the request: the proxy routes by
            // the host header and picks its certificate by the server name,
            // and the leaf is signed by skep's own authority, which
            // cloudflared has no reason to trust.
            args.extend([
                "--http-host-header".to_string(),
                host.clone(),
                "--origin-server-name".to_string(),
                host.clone(),
                "--no-tls-verify".to_string(),
            ]);
        }

        Ok(ServiceSpec::new(
            id,
            BinarySpec::managed(self.name(), version, self.program()),
            &data_dir,
        )
        .with_release(release)
        .with_display_name(self.display_name())
        .with_args(args)
        .with_ports([Port::new("metrics", metrics)])
        // Ready means a connection to the edge is registered, which is when
        // the public url starts answering.
        .with_health(HealthCheck::new(Probe::Http {
            port: metrics,
            path: "/ready".to_string(),
            expect: 200,
        }))
        .with_notice(Notice::new(MARKER)))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::Origin;

    #[test]
    fn the_spec_exposes_the_origin_and_watches_for_the_public_url() {
        let paths = Paths::new("/tmp/skep-spec-test");
        let request = Request::new()
            .with_tag(comb::Tag::Target("myapp-test".parse().unwrap()))
            .with_origin(Origin::site("myapp.test", 8443))
            .with_port("metrics", 20999);

        let spec = Cloudflared.spec(&request, &paths).unwrap();

        assert_eq!(spec.id.to_string(), "cloudflared@2026.8.3~myapp-test");
        assert!(spec.id.is_target() && !spec.id.is_branch());
        assert!(spec.data_dir.ends_with("targets/myapp-test"));
        assert!(spec.args.contains(&"https://127.0.0.1:8443".to_string()));
        assert!(spec.args.contains(&"--no-autoupdate".to_string()));
        assert!(spec.args.contains(&"--http-host-header".to_string()));
        assert!(spec.args.contains(&"--origin-server-name".to_string()));
        assert!(spec.args.contains(&"myapp.test".to_string()));
        assert_eq!(
            spec.health.probe,
            Probe::Http {
                port: 20999,
                path: "/ready".to_string(),
                expect: 200,
            }
        );
        assert_eq!(spec.notice, Some(Notice::new(MARKER)));
    }

    #[test]
    fn a_tunnel_with_nothing_behind_it_is_refused() {
        let paths = Paths::new("/tmp/skep-spec-test");
        let error = Cloudflared.spec(&Request::new(), &paths).unwrap_err();
        assert!(error.to_string().contains("skep share"), "{error}");
    }
}

#[cfg(test)]
mod origin_tests {
    use super::*;
    use crate::Origin;

    #[test]
    fn a_bare_service_is_reached_plainly_on_loopback() {
        let paths = Paths::new("/tmp/skep-spec-test");
        let request = Request::new()
            .with_tag(comb::Tag::Target("mailpit".parse().unwrap()))
            .with_origin(Origin::service(8025));
        let spec = Cloudflared.spec(&request, &paths).unwrap();
        assert!(spec.args.contains(&"http://127.0.0.1:8025".to_string()));
        assert!(!spec.args.contains(&"--no-tls-verify".to_string()));
    }
}
