//! Mailpit: a mail catcher that is a single static binary, which makes it the
//! simplest thing in the catalog and the one that proves the whole path.

use comb::{BinarySpec, HealthCheck, Paths, Platform, Port, Probe, Result, ServiceSpec};

use crate::{Pin, Request, ServiceAdapter};

pub struct Mailpit;

/// Generated by `scripts/pin-release.sh mailpit <version>`.
const PINS: &[Pin] = &[Pin {
    version: "1.31.0",
    platform: Platform::MacosArm64,
    url: "https://github.com/axllent/mailpit/releases/download/v1.31.0/mailpit-darwin-arm64.tar.gz",
    sha256: "108c4d8345368825924a61c492d96ffd82961f84cda5137c8e1ed03c1d2433b7",
    size: 10_092_536,
    strip_components: 0,
}];

const PORTS: &[(&str, u16)] = &[("http", 8025), ("smtp", 1025)];

impl ServiceAdapter for Mailpit {
    fn name(&self) -> &'static str {
        "mailpit"
    }

    fn display_name(&self) -> &'static str {
        "Mailpit"
    }

    fn program(&self) -> &'static str {
        "mailpit"
    }

    fn pins(&self) -> &'static [Pin] {
        PINS
    }

    fn default_version(&self) -> &'static str {
        "1.31.0"
    }

    fn default_ports(&self) -> &'static [(&'static str, u16)] {
        PORTS
    }

    fn spec(&self, request: &Request, paths: &Paths) -> Result<ServiceSpec> {
        let version = request.resolve_version(self)?;
        let release = crate::release(self, &version)?;
        let id = request.instance(self, &version)?;
        let http = request.port(self, "http")?;
        let smtp = request.port(self, "smtp")?;
        let data_dir = paths.data_dir(&id);
        let database = data_dir.join("mailpit.db");

        Ok(ServiceSpec::new(
            id,
            BinarySpec::managed(self.name(), version, self.program()),
            &data_dir,
        )
        .with_release(release)
        .with_display_name(self.display_name())
        .with_args([
            // Mailpit defaults to every interface. A local dev tool should not.
            "--listen".to_string(),
            format!("127.0.0.1:{http}"),
            "--smtp".to_string(),
            format!("127.0.0.1:{smtp}"),
            "--database".to_string(),
            database.display().to_string(),
        ])
        .with_ports([Port::new("http", http), Port::new("smtp", smtp)])
        .with_health(HealthCheck::new(Probe::Http {
            port: http,
            path: "/livez".to_string(),
            expect: 200,
        })))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_spec_binds_loopback_and_probes_the_health_endpoint() {
        let paths = Paths::new("/tmp/skep-spec-test");
        let request = Request::new().with_port("http", 9025);

        let spec = Mailpit.spec(&request, &paths).unwrap();

        assert_eq!(spec.id.to_string(), "mailpit@1.31.0");
        assert_eq!(spec.display_name, "Mailpit");
        assert!(spec.args.contains(&"127.0.0.1:9025".to_string()));
        assert!(
            !spec.args.iter().any(|arg| arg.contains("0.0.0.0")),
            "must not bind every interface"
        );
        assert_eq!(spec.primary_port(), Some(9025));
        assert_eq!(
            spec.health.probe,
            Probe::Http {
                port: 9025,
                path: "/livez".to_string(),
                expect: 200,
            }
        );
        assert!(spec.data_dir.ends_with("data/mailpit/1.31.0/main"));
    }

    #[test]
    fn a_label_makes_a_separate_instance_with_its_own_data() {
        let paths = Paths::new("/tmp/skep-spec-test");
        let request = Request::new().with_label("scratch".parse().unwrap());

        let spec = Mailpit.spec(&request, &paths).unwrap();

        assert_eq!(spec.id.to_string(), "mailpit@1.31.0:scratch");
        assert!(spec.data_dir.ends_with("branches/scratch"));
    }
}
