//! MongoDB. The only v1 service that needs no setup step: mongod builds its
//! own files inside a data directory that already exists.

use comb::{BinarySpec, HealthCheck, Paths, Platform, Port, Probe, Result, ServiceSpec};

use crate::{Pin, Request, ServiceAdapter};

pub struct Mongodb;

/// Generated by `scripts/pin-release.sh mongodb <version>`.
const PINS: &[Pin] = &[Pin {
    version: "8.0.29",
    platform: Platform::MacosArm64,
    url: "https://fastdl.mongodb.org/osx/mongodb-macos-arm64-8.0.29.tgz",
    sha256: "d2ed296a7a0a653dd5d2d7867a2589a7ad3f64b95fa3f05722f5414afaa28b4c",
    size: 81_624_386,
    strip_components: 1,
}];

const PORTS: &[(&str, u16)] = &[("mongodb", 27017)];

impl ServiceAdapter for Mongodb {
    fn name(&self) -> &'static str {
        "mongodb"
    }

    fn display_name(&self) -> &'static str {
        "MongoDB"
    }

    fn program(&self) -> &'static str {
        "bin/mongod"
    }

    fn pins(&self) -> &'static [Pin] {
        PINS
    }

    fn default_version(&self) -> &'static str {
        "8.0.29"
    }

    fn default_ports(&self) -> &'static [(&'static str, u16)] {
        PORTS
    }

    fn spec(&self, request: &Request, paths: &Paths) -> Result<ServiceSpec> {
        let version = request.resolve_version(self)?;
        let release = crate::release(self, &version)?;
        let id = request.instance(self, &version)?;
        let port = request.port(self, "mongodb")?;
        let data_dir = paths.data_dir(&id);

        Ok(ServiceSpec::new(
            id,
            BinarySpec::managed(self.name(), version, self.program()),
            &data_dir,
        )
        .with_display_name(self.display_name())
        .with_release(release)
        .with_args([
            "--dbpath".to_string(),
            data_dir.display().to_string(),
            "--port".to_string(),
            port.to_string(),
            "--bind_ip".to_string(),
            "127.0.0.1".to_string(),
        ])
        .with_ports([Port::new("mongodb", port)])
        .with_health(HealthCheck::new(Probe::Mongo { port })))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use comb::StopSignal;

    #[test]
    fn it_serves_loopback_only_and_needs_no_setup() {
        let spec = Mongodb
            .spec(&Request::new(), &Paths::new("/tmp/skep-mongo-spec"))
            .unwrap();

        assert!(spec.prepare.is_empty(), "mongod builds its own files");
        assert!(spec.args.contains(&"127.0.0.1".to_string()));
        assert_eq!(spec.health.probe, Probe::Mongo { port: 27017 });
        // mongod shuts down cleanly on SIGTERM.
        assert_eq!(spec.shutdown.signal, StopSignal::Term);
        assert!(
            spec.args.contains(&spec.data_dir.display().to_string()),
            "it should serve from its own data directory"
        );
    }
}
