//! MySQL. Like Postgres it needs a data directory built before it can serve,
//! but unlike Postgres it reads SIGTERM as the shutdown it should be, so it
//! keeps the default stop signal.

use comb::{
    BinarySpec, HealthCheck, Paths, Platform, Port, PrepareStep, Probe, Result, ServiceSpec,
};

use crate::{Pin, Request, ServiceAdapter};

pub struct Mysql;

/// Generated by `scripts/pin-release.sh mysql <version>`.
const PINS: &[Pin] = &[Pin {
    version: "8.4.6",
    platform: Platform::MacosArm64,
    url: "https://dev.mysql.com/get/Downloads/MySQL-8.4/mysql-8.4.6-macos15-arm64.tar.gz",
    sha256: "56ac9150b9d8fc757a36a2661a1214f5b09e5352d0a220e7a6c302685a5fca10",
    size: 166_683_072,
    strip_components: 1,
}];

const PORTS: &[(&str, u16)] = &[("mysql", 3306)];

impl ServiceAdapter for Mysql {
    fn name(&self) -> &'static str {
        "mysql"
    }

    fn display_name(&self) -> &'static str {
        "MySQL"
    }

    fn program(&self) -> &'static str {
        "bin/mysqld"
    }

    fn pins(&self) -> &'static [Pin] {
        PINS
    }

    fn default_version(&self) -> &'static str {
        "8.4.6"
    }

    fn default_ports(&self) -> &'static [(&'static str, u16)] {
        PORTS
    }

    fn spec(&self, request: &Request, paths: &Paths) -> Result<ServiceSpec> {
        let version = request.resolve_version(self)?;
        let release = crate::release(self, &version)?;
        let id = request.instance(self, &version)?;
        let port = request.port(self, "mysql")?;
        let data_dir = paths.data_dir(&id);
        let base_dir = paths.binary_dir(self.name(), &version);

        // Built in scratch and renamed in, so auto.cnf existing proves a
        // complete data directory rather than an interrupted one.
        let initialise = PrepareStep::new(
            "initialise the database",
            BinarySpec::managed(self.name(), version.clone(), self.program()),
        )
        .with_args([
            "--initialize-insecure".to_string(),
            "--datadir={output}".to_string(),
            format!("--basedir={}", base_dir.display()),
        ])
        .unless_exists(data_dir.join("auto.cnf"))
        .produces(&data_dir);

        Ok(ServiceSpec::new(
            id,
            BinarySpec::managed(self.name(), version, self.program()),
            &data_dir,
        )
        .with_display_name(self.display_name())
        .with_release(release)
        .with_args([
            format!("--datadir={}", data_dir.display()),
            format!("--basedir={}", base_dir.display()),
            format!("--port={port}"),
            "--bind-address=127.0.0.1".to_string(),
            // Short by necessity: a unix socket path is capped at 103 bytes and
            // the data directory is far too deep. The port keeps it unique.
            format!("--socket=/tmp/skep-mysql-{port}.sock"),
            // The X protocol would quietly claim a second port nobody asked for.
            "--mysqlx=OFF".to_string(),
        ])
        .with_prepare([initialise])
        .with_ports([Port::new("mysql", port)])
        .with_health(HealthCheck::new(Probe::Mysql { port })))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use comb::StopSignal;

    fn spec() -> ServiceSpec {
        Mysql
            .spec(&Request::new(), &Paths::new("/tmp/skep-mysql-spec"))
            .unwrap()
    }

    #[test]
    fn setup_writes_to_scratch_and_is_guarded() {
        let spec = spec();
        let step = &spec.prepare[0];

        assert_eq!(step.produces.as_deref(), Some(spec.data_dir.as_path()));
        assert_eq!(
            step.unless_exists.as_deref(),
            Some(spec.data_dir.join("auto.cnf").as_path())
        );
        assert!(step.args.iter().any(|arg| arg.contains("{output}")));
        assert!(
            !step
                .args
                .iter()
                .any(|arg| arg == &format!("--datadir={}", spec.data_dir.display())),
            "setup must not write straight to the final directory"
        );
    }

    #[test]
    fn it_keeps_to_loopback_and_claims_only_the_port_it_asked_for() {
        let spec = spec();

        assert!(spec.args.contains(&"--bind-address=127.0.0.1".to_string()));
        assert!(
            spec.args.contains(&"--mysqlx=OFF".to_string()),
            "the X protocol would take a second port"
        );
        assert_eq!(spec.ports.len(), 1);
        assert_eq!(spec.health.probe, Probe::Mysql { port: 3306 });
        // MySQL shuts down cleanly on SIGTERM, so it keeps the default.
        assert_eq!(spec.shutdown.signal, StopSignal::Term);

        let socket = spec
            .args
            .iter()
            .find(|arg| arg.starts_with("--socket="))
            .unwrap();
        assert!(socket.len() < 103, "socket path is too long: {socket}");
    }
}
