//! Postgres: the first adapter that needs setup before it can serve, and the
//! first whose readiness question has a real answer beyond "is the port open".

use std::time::Duration;

use comb::{
    BinarySpec, HealthCheck, Paths, Platform, Port, PrepareStep, Probe, Result, ServiceSpec,
    ShutdownSpec, StopSignal,
};

use crate::{Pin, Request, ServiceAdapter};

pub struct Postgres;

/// The superuser initdb creates and the probe connects as.
const SUPERUSER: &str = "skep";

/// Kept short on purpose. See the note where it is used.
const SOCKET_DIR: &str = "/tmp";

/// Generated by `scripts/pin-release.sh postgres <version>`. These come from a
/// third-party redistribution rather than postgresql.org, so the hash below is
/// the trust root, not a convenience.
const PINS: &[Pin] = &[
    Pin {
        version: "17.6.0",
        platform: Platform::MacosArm64,
        url: "https://github.com/theseus-rs/postgresql-binaries/releases/download/17.6.0/postgresql-17.6.0-aarch64-apple-darwin.tar.gz",
        sha256: "4d39534c9359ce04a6b1781111579e425d95c7ae2c8abe3ddfd6808b6ad19a5b",
        size: 9_941_919,
        strip_components: 1,
    },
    Pin {
        version: "16.10.0",
        platform: Platform::MacosArm64,
        url: "https://github.com/theseus-rs/postgresql-binaries/releases/download/16.10.0/postgresql-16.10.0-aarch64-apple-darwin.tar.gz",
        sha256: "8a21a0affdbd0056eb09bf2600769cf91450706ccafe5a86817fabc1b05c9087",
        size: 9_348_424,
        strip_components: 1,
    },
    Pin {
        version: "15.14.0",
        platform: Platform::MacosArm64,
        url: "https://github.com/theseus-rs/postgresql-binaries/releases/download/15.14.0/postgresql-15.14.0-aarch64-apple-darwin.tar.gz",
        sha256: "17bdbfaa1e52d78f03da7b6b21b473e9b78017cca0f59aed8a581b1ac86a43ed",
        size: 9_116_307,
        strip_components: 1,
    },
];

const PORTS: &[(&str, u16)] = &[("postgres", 5432)];

impl ServiceAdapter for Postgres {
    fn name(&self) -> &'static str {
        "postgres"
    }

    fn display_name(&self) -> &'static str {
        "PostgreSQL"
    }

    fn program(&self) -> &'static str {
        "bin/postgres"
    }

    fn pins(&self) -> &'static [Pin] {
        PINS
    }

    fn default_version(&self) -> &'static str {
        "17.6.0"
    }

    fn default_ports(&self) -> &'static [(&'static str, u16)] {
        PORTS
    }

    fn spec(&self, request: &Request, paths: &Paths) -> Result<ServiceSpec> {
        let version = request.resolve_version(self)?;
        let id = request.instance(self, &version)?;
        let port = request.port(self, "postgres")?;
        let data_dir = paths.data_dir(&id);

        // initdb writes to scratch and the directory is renamed in only on
        // success, so PG_VERSION existing proves a complete cluster.
        let initialise = PrepareStep::new(
            "initialise the database",
            BinarySpec::managed(self.name(), version.clone(), "bin/initdb"),
        )
        .with_args([
            "--pgdata={output}".to_string(),
            format!("--username={SUPERUSER}"),
            "--auth=trust".to_string(),
            "--encoding=UTF8".to_string(),
            "--no-sync".to_string(),
        ])
        .unless_exists(data_dir.join("PG_VERSION"))
        .produces(&data_dir);

        Ok(ServiceSpec::new(
            id,
            BinarySpec::managed(self.name(), version, self.program()),
            &data_dir,
        )
        .with_display_name(self.display_name())
        .with_args([
            "-D".to_string(),
            data_dir.display().to_string(),
            "-p".to_string(),
            port.to_string(),
            "-c".to_string(),
            "listen_addresses=127.0.0.1".to_string(),
            // The socket cannot live in the data directory: a unix socket path
            // is capped at 103 bytes and our nested data paths blow through it.
            // The port already makes it unique.
            "-k".to_string(),
            SOCKET_DIR.to_string(),
        ])
        .with_prepare([initialise])
        .with_ports([Port::new("postgres", port)])
        .with_health(HealthCheck::new(Probe::Postgres {
            port,
            user: SUPERUSER.to_string(),
            database: "postgres".to_string(),
        }))
        // SIGTERM is a smart shutdown that waits for every client to
        // disconnect. A dev tool wants the fast one, which checkpoints and
        // exits, so the next start needs no recovery.
        .with_shutdown(ShutdownSpec::new(StopSignal::Int, Duration::from_secs(30))))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn setup_is_guarded_and_produces_the_data_directory() {
        let paths = Paths::new("/tmp/skep-pg-spec");
        let spec = Postgres.spec(&Request::new(), &paths).unwrap();
        let step = &spec.prepare[0];

        assert_eq!(spec.id.to_string(), "postgres@17.6.0");
        assert_eq!(
            step.unless_exists.as_deref(),
            Some(spec.data_dir.join("PG_VERSION").as_path())
        );
        assert_eq!(step.produces.as_deref(), Some(spec.data_dir.as_path()));
        // initdb must write to scratch, never straight to the final directory.
        assert!(step.args.iter().any(|arg| arg.contains("{output}")));
        assert!(
            !step
                .args
                .iter()
                .any(|arg| arg.contains(&spec.data_dir.display().to_string())),
            "setup should not point at the final directory"
        );
    }

    #[test]
    fn it_asks_for_a_fast_shutdown_and_a_loopback_listener() {
        let spec = Postgres
            .spec(&Request::new(), &Paths::new("/tmp/skep-pg-spec"))
            .unwrap();

        assert_eq!(spec.shutdown.signal, StopSignal::Int);
        assert!(
            spec.args
                .contains(&"listen_addresses=127.0.0.1".to_string())
        );
        // A unix socket path is capped at 103 bytes, so it must not inherit
        // the depth of the data directory.
        let socket = format!("{SOCKET_DIR}/.s.PGSQL.65535");
        assert!(socket.len() < 104, "socket path {socket} is too long");
        assert_eq!(
            spec.health.probe,
            Probe::Postgres {
                port: 5432,
                user: SUPERUSER.to_string(),
                database: "postgres".to_string(),
            }
        );
    }

    #[test]
    fn every_major_is_pinned() {
        let majors: Vec<&str> = PINS
            .iter()
            .map(|pin| pin.version.split('.').next().unwrap())
            .collect();
        assert_eq!(majors, ["17", "16", "15"]);
    }
}
