//! Valkey. The one service with no macOS binary to download: upstream ships
//! prebuilt Linux tarballs and nothing for darwin, so on macOS the pinned
//! artifact is source and the compiler is the only unpinned input.

use comb::{BinarySpec, Build, HealthCheck, Paths, Platform, Port, Probe, Result, ServiceSpec};

use crate::{Pin, Request, ServiceAdapter};

pub struct Valkey;

/// Generated by `scripts/pin-release.sh valkey <version>`. This is a source
/// tarball, so the hash covers what we compile rather than what we run.
const PINS: &[Pin] = &[Pin {
    version: "9.1.1",
    platform: Platform::MacosArm64,
    url: "https://github.com/valkey-io/valkey/archive/refs/tags/9.1.1.tar.gz",
    sha256: "7d7232acd1b8a49b4e05d07a00b3ca8c801ae06ab633ca6a3423bc5f385ab7ee",
    size: 4_391_242,
    strip_components: 1,
}];

const PORTS: &[(&str, u16)] = &[("valkey", 6379)];

impl ServiceAdapter for Valkey {
    fn name(&self) -> &'static str {
        "valkey"
    }

    fn display_name(&self) -> &'static str {
        "Valkey"
    }

    fn program(&self) -> &'static str {
        "src/valkey-server"
    }

    fn pins(&self) -> &'static [Pin] {
        PINS
    }

    fn default_version(&self) -> &'static str {
        "9.1.1"
    }

    fn default_ports(&self) -> &'static [(&'static str, u16)] {
        PORTS
    }

    fn build(&self) -> Option<Build> {
        Some(Build {
            program: "make".to_string(),
            args: vec![format!(
                "-j{}",
                std::thread::available_parallelism().map_or(4, |threads| threads.get())
            )],
            // Linking is not working: this runs with --version before anything
            // is promoted.
            verify: "src/valkey-server".to_string(),
            // A build tree is mostly object files. Keep the two binaries a
            // person actually uses.
            keep: vec![
                "src/valkey-server".to_string(),
                "src/valkey-cli".to_string(),
            ],
        })
    }

    fn spec(&self, request: &Request, paths: &Paths) -> Result<ServiceSpec> {
        let version = request.resolve_version(self)?;
        let id = request.instance(self, &version)?;
        let port = request.port(self, "valkey")?;
        let data_dir = paths.data_dir(&id);

        let release = crate::release(self, &version)?;

        Ok(ServiceSpec::new(
            id,
            BinarySpec::managed(self.name(), version, self.program()),
            &data_dir,
        )
        .with_display_name(self.display_name())
        .with_release(release)
        .with_args([
            "--port".to_string(),
            port.to_string(),
            "--bind".to_string(),
            "127.0.0.1".to_string(),
            "--dir".to_string(),
            data_dir.display().to_string(),
            // Without this it daemonises and the engine loses its child.
            "--daemonize".to_string(),
            "no".to_string(),
        ])
        .with_ports([Port::new("valkey", port)])
        .with_health(HealthCheck::new(Probe::Resp { port })))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn it_is_built_from_source_and_verified_before_it_is_kept() {
        let spec = Valkey
            .spec(&Request::new(), &Paths::new("/tmp/skep-valkey-spec"))
            .unwrap();
        let build = spec.release.as_ref().unwrap().build.as_ref().unwrap();

        assert_eq!(build.program, "make");
        assert_eq!(build.verify, "src/valkey-server");
        assert!(
            build.keep.contains(&"src/valkey-server".to_string()),
            "the server itself must survive the harvest"
        );
        assert!(
            !build.keep.iter().any(|kept| kept.ends_with(".o")),
            "object files should not be kept forever"
        );
    }

    #[test]
    fn it_stays_on_loopback_and_in_the_foreground() {
        let spec = Valkey
            .spec(&Request::new(), &Paths::new("/tmp/skep-valkey-spec"))
            .unwrap();

        assert!(spec.args.contains(&"127.0.0.1".to_string()));
        let daemonize = spec
            .args
            .iter()
            .position(|arg| arg == "--daemonize")
            .unwrap();
        assert_eq!(
            spec.args[daemonize + 1],
            "no",
            "a daemonised child is a child the engine cannot supervise"
        );
        assert_eq!(spec.health.probe, Probe::Resp { port: 6379 });
    }
}
